version: 2
updates:
  # Enable version updates for npm ecosystem (works with Bun's package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    reviewers:
      - "sylva"
    assignees:
      - "sylva"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      # Group biome updates together
      biome:
        patterns:
          - "@biomejs/biome"
        update-types:
          - "minor"
          - "patch"
      # Group Next.js related packages
      nextjs:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - "minor"
          - "patch"
      # Group Radix UI components
      radix-ui:
        patterns:
          - "@radix-ui/*"
        update-types:
          - "minor"
          - "patch"
      # Group development dependencies
      dev-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "tailwindcss"
          - "@tailwindcss/*"
          - "postcss"
          - "autoprefixer"
        update-types:
          - "minor"
          - "patch"
      # Group testing dependencies (when added)
      testing:
        patterns:
          - "@testing-library/*"
          - "jest"
          - "vitest"
        update-types:
          - "minor"
          - "patch"